# 🍵 , Hanji Kaise ho aap sabhi this is 29th day of #100Days_Of_Python I'm back and ready to code.let's start to do code.

"""

Today i create a password  manager using python tkinter module that save our password emial id and website or app name in local system

It is very usefull app

So, Let's start to do code.

"""

"""
# Use a grid and columnspan in tkinter

from tkinter import *

window=Tk()

r=Label(bg="red",width=20,height=5)
r.grid(row=0,column=0)

g=Label(bg="green",width=20,height=5)
g.grid(row=1,column=1)

b=Label(bg="blue",width=20,height=5)
b.grid(row=2,column=0,columnspan=2)

# Columnspan is attribute that's can streach a row enitre any columns

window.mainloop()

"""
# email_entry['fg'] = 'grey'

"""
# Password Mannager Fnc Steps

Create a fnc called save()

Write to the data inside the entries to a data.txt file when the Add button is clicked.

Each website,email,and password combination should be on a new line inside the file.

All fields need to be cleared after Add button is presssed.

"""

